db:
  port: 5434
  sslmode: disable
  host:   165.232.68.67
  username: postgres
  dbname: postgres

http:
  port: 82
  MaxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

grpc:
  port: 58082

grpcFD:
  port: 58081
  host: 165.232.68.67
